# Defina o namespace
namespace: 

# Quantidade de Replicas
replicas: 1

# Informe os dados dos PODs:
containers:
  front: 
    imagem: registry.v2.unicoob.local/app:v1.0
    resources:
      memory: 100Mi
      cpu: 0.5
    ports:
      http-web:
        port: 80
        containerPort: 8080
        type: ClusterIP
    volumes:
      # www:
      #   mountpath: /var/www
      #   storage: 100Mi
      #   acceess: ReadWriteMany

# Descomentar acima e renomear www para o nome do volume que desejar.
# Se precisar mais volumes, copiar as 3 linhas abaixo de volume e mudar nome, mountpath e tamanho.
# Se o mapeamento for para arquivo, ao invés de colocar 100Gi no storage, escrever "host"

# Escalar o container caso tenha utilização de CPU acima de X valor (disabled/enabled)
autoscaling:
  auto: disabled
  min: 1
  max: 5
  cpuUtilization: 70

# Definir o dns da aplicação
ingress:
  host: #seudns
  path: /sistema
  tls: unicoob-secret

# Definir as variaveis. 
# Pode colocar chave valor uma embaixo da outra.
vars:
#  chave1: valor1
#  chave2: valor2
#  chave3: valor3
#  chave4: valor4

# Definir as variaveis sensiveis (Senhas). 
# Pode colocar chave valor uma embaixo da outra.
# Será convertido para base64 e colocado entre aspas automático.
secrets:
#  chave1: valor1
#  chave2: valor2
#  chave3: valor3

 # Tem metricas? (disabled/enabled)
 # Caso tenha, alterar para sim.
metrics: disabled