# Defina o namespace
namespace: 

# Quantidade de Replicas
replicas: 1

# Informe os dados dos PODs:
containers:
  front: 
    imagem: julianorib/mysite:v2.0
    resources:
      memory: 100Mi
      cpu: 0.5
    ports:
      http-web:
        port: 80
        containerPort: 8080
        type: ClusterIP
    volumes:
      # www:
      #   mountpath: /var/www
      #   storage: 100Mi

# Escalar o container caso tenha utilização de CPU acima de X valor (disabled/enabled)
autoscaling:
  auto: disabled
  min: 1
  max: 5
  cpuUtilization: 70

# Definir o dns da aplicação
ingress:
  host: xpto.domain.local
  path: /sistema
  tls: tls-secret

# Definir as variaveis. 
# Pode colocar chave valor uma embaixo da outra.
vars:
 chave1: valor1
 chave2: valor2
 chave3: valor3
 chave4: valor4

# Definir as variaveis sensiveis (Senhas). 
# Pode colocar chave valor uma embaixo da outra.
# Será convertido para base64 e colocado entre aspas automático.
secrets:
 chave1: valor1
 chave2: valor2
 chave3: valor3

 # Tem metricas? (disabled/enabled)
 # Caso tenha, alterar para sim.
metrics: disabled