apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec: 
      containers:
        - name: meucontainer
          image: julianorib/page-blue


## kubectl apply -f deployment.yaml
## kubectl get pods
## kubectl get replicaset
## kubectl get deployment
## kubectl describe deployment meudeploy
## kubectl port-forward deployment/meudeploy 8080:80
## kubectl delete deployment meudeploy