apiVersion: v1
kind: Pod
metadata:
  name: meupod
spec: 
  containers:
    - name:  nginx
      image: nginx

## kubectl apply -f pod.yaml

## kubectl get pods

## kubectl describe pod meupod

## kubectl port-forward pod/meupod 8080:80

## kubectl delete pod meupod
