apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: meureplicaset
spec:
  replicas: 5
  selector: 
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec: 
      containers:
        - name: meucontainer
          image: julianorib/page-blue


## kubectl apply -f replicaset.yaml
## kubectl get replicaset
## kubectl describe replicaset meureplicaset
## kubectl get pods
## kubectl port-forward replicaset/meureplicaset 8080:80
## kubectl scale replicaset meureplicaset --replicas=10
## kubectl scale replicaset meureplicaset --replicas=1
## kubectl delete replicaset meureplicaset


