apiVersion: v1
kind: Service
metadata:
  name: php-service
spec: 
  selector: 
    app: php
  ports:
  - protocols: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

## kubectl apply -f service-clusterip.yaml
## kubectl get services

## O service do tipo clusterIP é para comunicacao interna entre os Pods.

