stages:
  - build
  - upload

helm-build:
  stage: build
  rules:
  - if: $CI_COMMIT_TAG
  image:
    name: alpine/helm
    entrypoint: [""]
  script:
    - helm package template --version $CI_COMMIT_TAG
  artifacts:
    paths:
      - template-$CI_COMMIT_TAG.tgz

helm-upload:
  stage: upload
  rules:
  - if: $CI_COMMIT_TAG  
  needs: [helm-build]
  image:
    name: alpine/helm
    entrypoint: [""]
  script:
    - helm repo add template --username $USER --password $TOKEN https://GITLAB.DOMAIN.LOCAL/api/v4/projects/ID/packages/helm/stable --ca-file $CA
    - helm plugin install https://github.com/chartmuseum/helm-push 
    - helm cm-push template-$CI_COMMIT_TAG.tgz template --ca-file $CA
    