apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy8
spec:
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      labels: 
        app: nginx
    spec:
      serviceAccount: user-nginx
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-role-bind
subjects:
  - kind: ServiceAccount
    name: user-nginx
    namespace: default
roleRef:
  kind: Role
  name: nginx-role
  apiGroup: rbac.authorization.k8s.io
