apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingressroute
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: PathPrefix(`/`)
    services:
    - name: monitoring-grafana
      port: 80