apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.vars }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
  
  {{- $files := .Files }}
  {{- range $key, $value := .Files }}
  {{- if hasPrefix "conf/" $key }} 
  {{- with .}}
  {{ $key | trimPrefix "conf/" }}: |-
  {{ $files.Get $key | nindent 4  }} 
  {{- end }}
  {{- end }}
  {{- end }}
