{{- if eq .Values.autoscaling.auto "disabled" }}
{{- else }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: {{ .Values.autoscaling.min }}
  maxReplicas: {{ .Values.autoscaling.max }}
  targetCPUUtilizationPercentage: {{ .Values.autoscaling.cpuUtilization }}
{{- end }}