{{- range $key,$value := .Values.containers }}
{{- range $key,$value := .ports }}
{{- if eq $key "ssh"}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $.Release.Name }}-ssh
  namespace: {{ $.Values.namespace }}
spec:
  entryPoints:
  - ssh
  routes:
  - match: HostSNI(`*`)
    services:
    - name: ssh-{{ $.Release.Name }}
      port: 10022
{{- end }}
{{- end }}
{{- end }}
