{{- range $key,$value := .Values.containers }}
{{- range $key,$value := .ports }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $key }}-{{ $.Release.Name }}
  namespace: {{ $.Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ $.Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    ports:
    - protocol: TCP
      port: {{ .containerPort }}  
---
{{- end}}
{{- end }}