{{- range $key,$value := .Values.containers }}
{{- range $key,$value := .volumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $key }}-{{ $.Release.Name }}
  namespace: {{ $.Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      {{- with .}}
      storage: {{ .storage }}
{{- end }}
---
{{- end }}
{{- end }}