{{- range $key,$value := .Values.containers }}
{{- range $key,$value := .volumes }}
{{- with .}}
{{- if eq .storage "host" }}
{{- else }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $key }}-{{ $.Release.Name }}
  namespace: {{ $.Values.namespace }}
spec:
  accessModes:
    - {{ .access }}
  storageClassName: nfs-client
  resources:
    requests:
      storage: {{ .storage }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}