{{- range $key,$value := .Values.containers }}
{{- range $key,$value := .ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}-{{ $.Release.Name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $.Release.Name }}
spec:
   selector:
     app: {{ $.Release.Name }}
   {{- with .}}
   ports:
     - name: {{ $key }}
       port: {{ .port }}
       targetPort: {{ .containerPort }}
   type: {{ .type }}
{{- end }}
---
{{- end }}
{{- end }}
